// app/dashboard/requests/page.tsx
'use client';

import { useState, useMemo } from 'react';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Textarea } from '@/components/ui/textarea';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from '@/components/ui/alert-dialog';
import {
  Sheet,
  SheetContent,
  SheetHeader,
  SheetTitle,
} from '@/components/ui/sheet';
import {
  MessageSquare,
  Clock,
  CheckCircle,
  XCircle,
  AlertTriangle,
  Wrench,
  Droplet,
  Zap,
  Wifi,
  Home,
  User,
  Calendar,
  Phone,
  X,
  Check,
  MessageCircle,
  Play,
  CheckCircle2,
} from 'lucide-react';
import { cn } from '@/lib/utils';
import { toast } from 'sonner';

// Request types
type RequestStatus = 'pending' | 'in_progress' | 'completed' | 'rejected';
type RequestCategory = 'maintenance' | 'plumbing' | 'electrical' | 'internet' | 'other';
type RequestPriority = 'important' | 'normal';

interface Request {
  id: string;
  tenantName: string;
  tenantPhone: string;
  roomNumber: string;
  buildingName: string;
  category: RequestCategory;
  title: string;
  description: string;
  status: RequestStatus;
  priority: RequestPriority;
  createdAt: string;
  updatedAt: string;
  response?: string;
}

// Status config
const statusConfig: Record<RequestStatus, { label: string; color: string; bgColor: string; icon: typeof Clock }> = {
  pending: {
    label: 'Chờ xử lý',
    color: 'text-amber-600',
    bgColor: 'bg-amber-50 border-amber-200',
    icon: Clock,
  },
  in_progress: {
    label: 'Đang xử lý',
    color: 'text-blue-600',
    bgColor: 'bg-blue-50 border-blue-200',
    icon: Wrench,
  },
  completed: {
    label: 'Hoàn thành',
    color: 'text-emerald-600',
    bgColor: 'bg-emerald-50 border-emerald-200',
    icon: CheckCircle,
  },
  rejected: {
    label: 'Từ chối',
    color: 'text-red-600',
    bgColor: 'bg-red-50 border-red-200',
    icon: XCircle,
  },
};

// Category config
const categoryConfig: Record<RequestCategory, { label: string; icon: typeof Wrench }> = {
  maintenance: { label: 'Sửa chữa', icon: Wrench },
  plumbing: { label: 'Nước', icon: Droplet },
  electrical: { label: 'Điện', icon: Zap },
  internet: { label: 'Internet', icon: Wifi },
  other: { label: 'Khác', icon: MessageSquare },
};

// Priority config
const priorityConfig: Record<RequestPriority, { label: string; color: string; bgColor: string }> = {
  important: {
    label: 'Quan trọng',
    color: 'text-red-600',
    bgColor: 'bg-red-50 border-red-200',
  },
  normal: {
    label: 'Thông thường',
    color: 'text-slate-600',
    bgColor: 'bg-slate-50 border-slate-200',
  },
};

// Generate mock requests
const generateRequests = (): Request[] => {
  return [
    {
      id: '1',
      tenantName: 'Nguyễn Văn An',
      tenantPhone: '0901234567',
      roomNumber: '301',
      buildingName: 'HAGL 3',
      category: 'plumbing',
      title: 'Bồn cầu bị tắc',
      description: 'Bồn cầu trong phòng tắm bị tắc, nước không thoát được. Đã thử dùng cây thông nhưng không được.',
      status: 'pending',
      priority: 'important',
      createdAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
      updatedAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    },
    {
      id: '2',
      tenantName: 'Trần Thị Bình',
      tenantPhone: '0912345678',
      roomNumber: '205',
      buildingName: 'Phú Hoàng Anh',
      category: 'electrical',
      title: 'Đèn phòng ngủ không sáng',
      description: 'Đèn trần phòng ngủ bị hỏng, đã thử thay bóng nhưng vẫn không sáng. Có thể bị hỏng công tắc hoặc dây điện.',
      status: 'in_progress',
      priority: 'important',
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
      updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
      response: 'Đã ghi nhận. Thợ điện sẽ đến kiểm tra vào chiều nay.',
    },
    {
      id: '3',
      tenantName: 'Lê Văn Cường',
      tenantPhone: '0923456789',
      roomNumber: '402',
      buildingName: 'SSR',
      category: 'internet',
      title: 'Wifi yếu, hay bị ngắt',
      description: 'Wifi trong phòng rất yếu, thường xuyên bị ngắt kết nối. Đã thử restart router nhưng không cải thiện.',
      status: 'pending',
      priority: 'normal',
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
      updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
    },
    {
      id: '4',
      tenantName: 'Phạm Thị Dung',
      tenantPhone: '0934567890',
      roomNumber: '108',
      buildingName: 'HAGL 3',
      category: 'maintenance',
      title: 'Cửa sổ không đóng được',
      description: 'Cửa sổ phòng khách bị kẹt, không đóng được. Khi mưa nước tạt vào phòng.',
      status: 'completed',
      priority: 'important',
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
      updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
      response: 'Đã sửa xong cửa sổ. Bản lề bị hỏng đã được thay mới.',
    },
    {
      id: '5',
      tenantName: 'Hoàng Văn Em',
      tenantPhone: '0945678901',
      roomNumber: '512',
      buildingName: 'Sunrise',
      category: 'plumbing',
      title: 'Vòi nước bồn rửa bị rỉ',
      description: 'Vòi nước bồn rửa mặt bị rỉ nước, cần thay mới.',
      status: 'rejected',
      priority: 'normal',
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
      updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
      response: 'Vòi nước do khách tự lắp, không thuộc trách nhiệm bảo trì của tòa nhà. Vui lòng tự sửa chữa.',
    },
    {
      id: '6',
      tenantName: 'Nguyễn Thị Phương',
      tenantPhone: '0956789012',
      roomNumber: '210',
      buildingName: 'Phú Hoàng Anh',
      category: 'other',
      title: 'Yêu cầu thêm kệ tường',
      description: 'Muốn xin phép lắp thêm kệ treo tường trong phòng ngủ để để đồ.',
      status: 'pending',
      priority: 'normal',
      createdAt: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
      updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
    },
  ];
};

export default function RequestsPage() {
  const [requests, setRequests] = useState<Request[]>(generateRequests);
  const [statusFilter, setStatusFilter] = useState<'all' | RequestStatus>('all');
  const [categoryFilter, setCategoryFilter] = useState<'all' | RequestCategory>('all');
  const [selectedRequest, setSelectedRequest] = useState<Request | null>(null);
  const [sheetOpen, setSheetOpen] = useState(false);
  const [responseText, setResponseText] = useState('');
  const [actionDialogOpen, setActionDialogOpen] = useState(false);
  const [actionType, setActionType] = useState<'complete' | 'reject' | null>(null);

  const filteredRequests = useMemo(() => {
    return requests.filter(r => {
      const matchStatus = statusFilter === 'all' || r.status === statusFilter;
      const matchCategory = categoryFilter === 'all' || r.category === categoryFilter;
      return matchStatus && matchCategory;
    });
  }, [requests, statusFilter, categoryFilter]);

  const stats = useMemo(() => {
    return {
      pending: requests.filter(r => r.status === 'pending').length,
      in_progress: requests.filter(r => r.status === 'in_progress').length,
      completed: requests.filter(r => r.status === 'completed').length,
      rejected: requests.filter(r => r.status === 'rejected').length,
    };
  }, [requests]);

  const formatTime = (dateString: string) => {
    const date = new Date(dateString);
    const now = new Date();
    const diffMs = now.getTime() - date.getTime();
    const diffMins = Math.floor(diffMs / (1000 * 60));
    const diffHours = Math.floor(diffMs / (1000 * 60 * 60));
    const diffDays = Math.floor(diffMs / (1000 * 60 * 60 * 24));

    if (diffMins < 60) return `${diffMins} phút trước`;
    if (diffHours < 24) return `${diffHours} giờ trước`;
    if (diffDays < 7) return `${diffDays} ngày trước`;
    return date.toLocaleDateString('vi-VN');
  };

  const handleRequestClick = (request: Request) => {
    setSelectedRequest(request);
    setResponseText(request.response || '');
    setSheetOpen(true);
  };

  const handleStartProgress = () => {
    if (!selectedRequest) return;
    setRequests(prev =>
      prev.map(r =>
        r.id === selectedRequest.id
          ? { ...r, status: 'in_progress' as RequestStatus, updatedAt: new Date().toISOString() }
          : r
      )
    );
    setSelectedRequest(prev => prev ? { ...prev, status: 'in_progress' } : null);
    toast.success('Đã chuyển sang trạng thái đang xử lý');
  };

  const handleActionClick = (type: 'complete' | 'reject') => {
    setActionType(type);
    setActionDialogOpen(true);
  };

  const handleConfirmAction = () => {
    if (!selectedRequest || !actionType) return;

    const newStatus = actionType === 'complete' ? 'completed' : 'rejected';
    setRequests(prev =>
      prev.map(r =>
        r.id === selectedRequest.id
          ? {
              ...r,
              status: newStatus as RequestStatus,
              response: responseText,
              updatedAt: new Date().toISOString(),
            }
          : r
      )
    );
    setSelectedRequest(prev =>
      prev ? { ...prev, status: newStatus as RequestStatus, response: responseText } : null
    );
    toast.success(actionType === 'complete' ? 'Đã hoàn thành yêu cầu' : 'Đã từ chối yêu cầu');
    setActionDialogOpen(false);
  };

  const handleSaveResponse = () => {
    if (!selectedRequest) return;
    setRequests(prev =>
      prev.map(r =>
        r.id === selectedRequest.id
          ? { ...r, response: responseText, updatedAt: new Date().toISOString() }
          : r
      )
    );
    toast.success('Đã lưu phản hồi');
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div>
        <h1 className="text-2xl font-bold">Yêu cầu của khách</h1>
        <p className="text-muted-foreground">
          {stats.pending > 0 ? (
            <span className="text-amber-600 font-medium">{stats.pending} yêu cầu chờ xử lý</span>
          ) : (
            'Không có yêu cầu chờ xử lý'
          )}
        </p>
      </div>

      {/* Stats */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
        {(Object.keys(statusConfig) as RequestStatus[]).map((status) => {
          const config = statusConfig[status];
          const StatusIcon = config.icon;
          const count = stats[status];
          return (
            <Card
              key={status}
              className={cn(
                'cursor-pointer transition-colors border',
                statusFilter === status
                  ? `border-2 ${config.bgColor}`
                  : 'hover:border-slate-300'
              )}
              onClick={() => setStatusFilter(statusFilter === status ? 'all' : status)}
            >
              <CardContent className="p-3 sm:p-4">
                <div className="flex items-center gap-2">
                  <StatusIcon className={cn('h-4 w-4', config.color)} />
                  <span className="text-xs sm:text-sm text-muted-foreground">{config.label}</span>
                </div>
                <p className={cn('text-lg sm:text-2xl font-bold', config.color)}>{count}</p>
              </CardContent>
            </Card>
          );
        })}
      </div>

      {/* Filter */}
      <div className="flex gap-3">
        <Select value={categoryFilter} onValueChange={(v) => setCategoryFilter(v as 'all' | RequestCategory)}>
          <SelectTrigger className="w-[180px]">
            <SelectValue placeholder="Danh mục" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="all">Tất cả danh mục</SelectItem>
            {Object.entries(categoryConfig).map(([key, config]) => (
              <SelectItem key={key} value={key}>
                <div className="flex items-center gap-2">
                  <config.icon className="h-4 w-4" />
                  {config.label}
                </div>
              </SelectItem>
            ))}
          </SelectContent>
        </Select>
        {(statusFilter !== 'all' || categoryFilter !== 'all') && (
          <Button
            variant="ghost"
            size="sm"
            onClick={() => {
              setStatusFilter('all');
              setCategoryFilter('all');
            }}
          >
            Xóa bộ lọc
          </Button>
        )}
      </div>

      {/* Requests List */}
      <div className="space-y-3">
        {filteredRequests.length === 0 ? (
          <Card>
            <CardContent className="p-12 text-center">
              <MessageSquare className="h-12 w-12 mx-auto text-muted-foreground mb-4" />
              <p className="text-muted-foreground font-medium mb-2">Không có yêu cầu</p>
              <p className="text-sm text-muted-foreground">
                {statusFilter !== 'all' || categoryFilter !== 'all'
                  ? 'Thử thay đổi bộ lọc để xem thêm yêu cầu'
                  : 'Chưa có yêu cầu nào từ khách thuê'}
              </p>
            </CardContent>
          </Card>
        ) : (
          filteredRequests.map((request) => {
            const categoryInfo = categoryConfig[request.category];

            return (
              <Card
                key={request.id}
                className="hover:bg-muted/50 transition-colors cursor-pointer"
                onClick={() => handleRequestClick(request)}
              >
                <CardContent className="p-4">
                  <div className="flex items-start justify-between gap-3">
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center gap-2 mb-1">
                        <h3 className="font-medium">{request.title}</h3>
                        {request.priority === 'important' && (
                          <span className="text-xs text-red-600">• Quan trọng</span>
                        )}
                      </div>
                      <p className="text-sm text-muted-foreground mb-2 line-clamp-1">
                        {request.description}
                      </p>
                      <div className="flex items-center gap-3 text-xs text-muted-foreground">
                        <span>P.{request.roomNumber} - {request.buildingName}</span>
                        <span>•</span>
                        <span>{request.tenantName}</span>
                        <span>•</span>
                        <span>{formatTime(request.createdAt)}</span>
                      </div>
                    </div>

                    {/* Quick Actions */}
                    <div className="shrink-0">
                      {request.status === 'pending' && (
                        <Button
                          variant="outline"
                          size="sm"
                          className="h-8 text-xs"
                          onClick={(e) => {
                            e.stopPropagation();
                            setRequests(prev =>
                              prev.map(r =>
                                r.id === request.id
                                  ? { ...r, status: 'in_progress' as RequestStatus, updatedAt: new Date().toISOString() }
                                  : r
                              )
                            );
                            toast.success('Đã chuyển sang đang xử lý');
                          }}
                        >
                          <Play className="h-3 w-3 mr-1" />
                          Xử lý
                        </Button>
                      )}
                      {request.status === 'in_progress' && (
                        <Button
                          variant="outline"
                          size="sm"
                          className="h-8 text-xs"
                          onClick={(e) => {
                            e.stopPropagation();
                            setSelectedRequest(request);
                            setResponseText(request.response || '');
                            handleActionClick('complete');
                          }}
                        >
                          <CheckCircle2 className="h-3 w-3 mr-1" />
                          Xong
                        </Button>
                      )}
                      {(request.status === 'completed' || request.status === 'rejected') && (
                        <span className="text-xs text-muted-foreground">
                          {request.status === 'completed' ? 'Đã xong' : 'Từ chối'}
                        </span>
                      )}
                    </div>
                  </div>
                </CardContent>
              </Card>
            );
          })
        )}
      </div>

      {/* Summary */}
      {filteredRequests.length > 0 && (
        <div className="text-center">
          <p className="text-sm text-muted-foreground">
            Hiển thị {filteredRequests.length} yêu cầu
          </p>
        </div>
      )}

      {/* Request Detail Sheet */}
      <Sheet open={sheetOpen} onOpenChange={setSheetOpen}>
        <SheetContent className="w-full sm:max-w-xl p-0 flex flex-col" hideCloseButton>
          {selectedRequest && (() => {
            const statusInfo = statusConfig[selectedRequest.status];
            const categoryInfo = categoryConfig[selectedRequest.category];
            const StatusIcon = statusInfo.icon;
            const CategoryIcon = categoryInfo.icon;

            return (
              <>
                {/* Fixed Header */}
                <div className="px-4 sm:px-6 py-4 sm:py-5 border-b bg-slate-50/80">
                  <SheetHeader>
                    <div className="flex items-center justify-between gap-3">
                      <Button
                        variant="ghost"
                        size="sm"
                        className="shrink-0"
                        onClick={() => setSheetOpen(false)}
                      >
                        <X className="h-4 w-4 mr-1" />
                        Đóng
                      </Button>
                      <SheetTitle className="flex-1 min-w-0 text-right">
                        <span className="text-lg truncate">{selectedRequest.title}</span>
                      </SheetTitle>
                    </div>
                  </SheetHeader>
                </div>

                {/* Scrollable Content */}
                <div className="flex-1 overflow-y-auto px-4 sm:px-6 py-4 space-y-4">
                  {/* Status & Priority */}
                  <div className="flex items-center gap-2 text-sm text-muted-foreground">
                    {selectedRequest.priority === 'important' && (
                      <span className="text-red-600 font-medium">Quan trọng</span>
                    )}
                    {selectedRequest.priority === 'important' && <span>•</span>}
                    <span>{statusInfo.label}</span>
                    <span>•</span>
                    <span>Cập nhật {formatTime(selectedRequest.updatedAt)}</span>
                  </div>

                  {/* Info */}
                  <div className="space-y-2 text-sm">
                    <div className="flex justify-between">
                      <span className="text-muted-foreground">Phòng</span>
                      <span>P.{selectedRequest.roomNumber} - {selectedRequest.buildingName}</span>
                    </div>
                    <div className="flex justify-between">
                      <span className="text-muted-foreground">Khách thuê</span>
                      <span>{selectedRequest.tenantName}</span>
                    </div>
                    <div className="flex justify-between">
                      <span className="text-muted-foreground">Điện thoại</span>
                      <a href={`tel:${selectedRequest.tenantPhone}`} className="text-blue-600">
                        {selectedRequest.tenantPhone}
                      </a>
                    </div>
                    <div className="flex justify-between">
                      <span className="text-muted-foreground">Ngày gửi</span>
                      <span>
                        {new Date(selectedRequest.createdAt).toLocaleDateString('vi-VN', {
                          day: 'numeric',
                          month: 'long',
                          year: 'numeric',
                          hour: '2-digit',
                          minute: '2-digit',
                        })}
                      </span>
                    </div>
                  </div>

                  {/* Description */}
                  <div className="pt-2">
                    <p className="text-sm text-muted-foreground mb-1">Nội dung</p>
                    <p className="text-sm">{selectedRequest.description}</p>
                  </div>

                  {/* Response */}
                  <div className="pt-2">
                    <p className="text-sm text-muted-foreground mb-1">Phản hồi</p>
                    {selectedRequest.status === 'completed' || selectedRequest.status === 'rejected' ? (
                      <p className="text-sm">{selectedRequest.response || 'Không có phản hồi'}</p>
                    ) : (
                      <div className="space-y-2">
                        <Textarea
                          placeholder="Nhập phản hồi cho khách thuê..."
                          value={responseText}
                          onChange={(e) => setResponseText(e.target.value)}
                          rows={3}
                        />
                        {selectedRequest.status === 'in_progress' && responseText !== (selectedRequest.response || '') && (
                          <Button variant="outline" size="sm" onClick={handleSaveResponse}>
                            Lưu phản hồi
                          </Button>
                        )}
                      </div>
                    )}
                  </div>

                  {/* Actions */}
                  {selectedRequest.status !== 'completed' && selectedRequest.status !== 'rejected' && (
                    <div className="flex gap-3 pt-4">
                      {selectedRequest.status === 'pending' && (
                        <Button className="flex-1" onClick={handleStartProgress}>
                          <Wrench className="h-4 w-4 mr-2" />
                          Bắt đầu xử lý
                        </Button>
                      )}
                      {selectedRequest.status === 'in_progress' && (
                        <>
                          <Button
                            variant="outline"
                            className="flex-1 text-red-600 hover:text-red-700 hover:bg-red-50"
                            onClick={() => handleActionClick('reject')}
                          >
                            Từ chối
                          </Button>
                          <Button
                            className="flex-1 bg-emerald-600 hover:bg-emerald-700"
                            onClick={() => handleActionClick('complete')}
                          >
                            Hoàn thành
                          </Button>
                        </>
                      )}
                    </div>
                  )}
                </div>
              </>
            );
          })()}
        </SheetContent>
      </Sheet>

      {/* Action Confirmation Dialog */}
      <AlertDialog open={actionDialogOpen} onOpenChange={setActionDialogOpen}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>
              {actionType === 'complete' ? 'Hoàn thành yêu cầu?' : 'Từ chối yêu cầu?'}
            </AlertDialogTitle>
            <AlertDialogDescription>
              {actionType === 'complete'
                ? 'Xác nhận đã hoàn thành xử lý yêu cầu này. Khách thuê sẽ nhận được thông báo.'
                : 'Xác nhận từ chối yêu cầu này. Khách thuê sẽ nhận được thông báo với lý do từ chối.'}
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>Hủy</AlertDialogCancel>
            <AlertDialogAction
              onClick={handleConfirmAction}
              className={actionType === 'complete' ? 'bg-emerald-600 hover:bg-emerald-700' : 'bg-red-600 hover:bg-red-700'}
            >
              {actionType === 'complete' ? 'Hoàn thành' : 'Từ chối'}
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </div>
  );
}

// src/routes/dashboard/requests/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { toast } from 'svelte-sonner';
  import { 
    Wrench, 
    X, 
    Check, 
    AlertTriangle,
    Clock,
    User,
    Calendar,
    MessageSquare,
    Loader2
  } from '@lucide/svelte';

  interface Request {
    id: string;
    tenantId: string;
    roomNumber: string;
    buildingName: string;
    category: string; // 'maintenance' | 'plumbing' | 'electrical' | 'internet' | 'other'
    title: string;
    description: string;
    imageUrl: string | null;
    status: string; // 'pending' | 'in_progress' | 'completed' | 'rejected'
    priority: string; // 'important' | 'normal'
    createdAt: string;
    response: string | null;
    tenant: {
      user: {
        name: string;
        phone: string;
      }
    };
  }

  let landlordId = $state<string | null>(null);
  let isLoading = $state(true);
  let requests = $state<Request[]>([]);
  let selectedRequest = $state<Request | null>(null);
  let isDetailOpen = $state(false);

  // Filters
  let statusFilter = $state('');
  let priorityFilter = $state('');

  // Response form states
  let replyText = $state('');
  let isSubmitting = $state(false);

  onMount(() => {
    const sessionStr = localStorage.getItem('roomio_user');
    if (!sessionStr) return;
    const session = JSON.parse(sessionStr);
    landlordId = session.landlordProfileId;
    fetchRequests(session.landlordProfileId);
  });

  async function fetchRequests(profileId: string) {
    isLoading = true;
    try {
      const res = await fetch(`/api/requests?landlordId=${profileId}`);
      const data = await res.json();
      if (res.ok) requests = data;
    } catch (e: any) {
      toast.error('Lỗi khi tải danh sách sự cố: ' + e.message);
    } finally {
      isLoading = false;
    }
  }

  async function updateRequestStatus(requestId: string, status: string) {
    if (isSubmitting) return;
    isSubmitting = true;

    try {
      const res = await fetch('/api/requests', {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          id: requestId,
          status,
          response: replyText || undefined
        })
      });
      const data = await res.json();

      if (!res.ok) throw new Error(data.error || 'Lỗi khi cập nhật sự cố');

      toast.success(`Đã cập nhật trạng thái sự cố sang: ${getStatusLabel(status)}`);
      isDetailOpen = false;
      selectedRequest = null;
      replyText = '';
      if (landlordId) fetchRequests(landlordId);
    } catch (err: any) {
      toast.error(err.message);
    } finally {
      isSubmitting = false;
    }
  }

  function getStatusLabel(status: string): string {
    const labels: Record<string, string> = {
      pending: 'Đang chờ',
      in_progress: 'Đang sửa',
      completed: 'Đã xong',
      rejected: 'Từ chối'
    };
    return labels[status] || status;
  }

  function getCategoryLabel(cat: string): string {
    const labels: Record<string, string> = {
      maintenance: 'Nội thất/Gia dụng',
      plumbing: 'Đường nước',
      electrical: 'Hệ thống điện',
      internet: 'Mạng Wifi',
      other: 'Khác'
    };
    return labels[cat] || cat;
  }

  // Filtered requests computed state
  const filteredRequests = $derived(() => {
    return requests.filter(req => {
      const matchStatus = statusFilter === '' || req.status === statusFilter;
      const matchPriority = priorityFilter === '' || req.priority === priorityFilter;
      return matchStatus && matchPriority;
    });
  });
</script>

<div class="space-y-6">
  <!-- Header -->
  <div>
    <h1 class="text-2xl font-black text-black">Báo Cáo Sự Cố</h1>
    <p class="text-zinc-650 text-sm mt-1 font-bold">Quản lý và giải quyết các yêu cầu sửa chữa từ khách thuê phòng</p>
  </div>

  <!-- Filters -->
  <div class="bg-white border-2 border-black p-4 rounded-lg shadow-secondary flex flex-wrap gap-4 items-center">
    <div class="space-y-1">
      <span class="text-[10px] font-bold text-zinc-650 uppercase tracking-wider block">Trạng thái sự cố</span>
      <select 
        bind:value={statusFilter}
        class="border-2 border-black px-3 py-2 text-sm rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-300 bg-white font-semibold text-black w-44"
      >
        <option value="">Tất cả trạng thái</option>
        <option value="pending">Đang chờ (Pending)</option>
        <option value="in_progress">Đang sửa (In Progress)</option>
        <option value="completed">Đã xong (Completed)</option>
        <option value="rejected">Từ chối (Rejected)</option>
      </select>
    </div>

    <div class="space-y-1">
      <span class="text-[10px] font-bold text-zinc-650 uppercase tracking-wider block">Mức độ khẩn cấp</span>
      <select 
        bind:value={priorityFilter}
        class="border-2 border-black px-3 py-2 text-sm rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-300 bg-white font-semibold text-black w-44"
      >
        <option value="">Tất cả</option>
        <option value="important">Khẩn cấp / Gấp</option>
        <option value="normal">Bình thường</option>
      </select>
    </div>
  </div>

  {#if isLoading}
    <div class="h-[50vh] w-full flex items-center justify-center">
      <Loader2 class="h-10 w-10 text-black animate-spin" />
    </div>
  {:else if filteredRequests().length === 0}
    <div class="bg-white border-2 border-black p-12 rounded-lg text-center max-w-md mx-auto shadow-secondary">
              <Wrench class="h-7 w-7" />
      <h3 class="font-black text-black text-lg">Không có yêu cầu sự cố</h3>
      <p class="text-zinc-650 text-sm mt-2 font-semibold">Tuyệt vời! Hiện tại không ghi nhận sự cố nào từ cư dân.</p>
    </div>
  {:else}
    <!-- Grid of incident cards -->
    <div class="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
      {#each filteredRequests() as req}
        {@const statusBadge = req.status === 'completed' ? 'bg-green-200 text-green-800' : req.status === 'in_progress' ? 'bg-blue-300 text-black' : req.status === 'rejected' ? 'bg-zinc-200 text-zinc-600' : 'bg-red-200 text-red-800'}

        <div
          onclick={() => { selectedRequest = req; replyText = req.response || ''; isDetailOpen = true; }}
          onkeydown={(e) => e.key === 'Enter' && (selectedRequest = req, replyText = req.response || '', isDetailOpen = true)}
          role="button"
          tabindex="0"
          class="border-2 border-black bg-white p-5 rounded-lg shadow-secondary hover:shadow-none hover:translate-x-[3px] hover:translate-y-[3px] active:translate-x-[3px] active:translate-y-[3px] active:shadow-none transition-all cursor-pointer text-left focus:outline-none focus:ring-2 focus:ring-blue-300"
        >
          <div class="flex justify-between items-start gap-2 mb-3">
            <div>
              <span class="text-[10px] px-2.5 py-0.5 rounded-full font-black uppercase tracking-wider border border-black {statusBadge}">
                {getStatusLabel(req.status)}
              </span>
              {#if req.priority === 'important'}
                <span class="text-[9px] px-2 py-0.5 ml-1.5 rounded-full font-black uppercase bg-red-500 text-black border border-black animate-pulse">
                  Gấp
                </span>
              {/if}
            </div>
            <span class="text-xs text-zinc-650 font-bold">{new Date(req.createdAt).toLocaleDateString('vi-VN')}</span>
          </div>

          <h3 class="font-black text-black text-base leading-tight truncate">{req.title}</h3>
          <p class="text-zinc-600 text-xs mt-1 truncate font-semibold">{req.buildingName} - Phòng {req.roomNumber}</p>
          <p class="text-zinc-500 text-xs mt-2 line-clamp-2 leading-relaxed font-semibold">{req.description}</p>

          <div class="border-t border-black/15 mt-4 pt-3 flex items-center justify-between text-xs text-zinc-650">
            <span class="flex items-center gap-1.5 font-bold">
              <User class="h-4 w-4 text-black" />
              {req.tenant.user.name}
            </span>
            <span class="bg-white border border-black text-black px-2 py-1 rounded-lg font-bold text-[9px] uppercase shadow-secondary">
              {getCategoryLabel(req.category)}
            </span>
          </div>
        </div>
      {/each}
    </div>
  {/if}

  <!-- Detail Dialog Drawer slide-over -->
  {#if isDetailOpen && selectedRequest}
    <!-- Overlay -->
    <div 
      class="fixed inset-0 bg-slate-900/50 backdrop-blur-sm z-50 flex justify-end"
      onclick={() => isDetailOpen = false}
      onkeydown={(e) => e.key === 'Escape' && (isDetailOpen = false)}
      role="button"
      tabindex="0"
    >
      <!-- Drawer Content: Brutallist Panel border-l-2 -->
      <div 
        class="bg-white w-full max-w-lg h-full border-l-2 border-black shadow-primary flex flex-col justify-between overflow-hidden animate-[slide-left_0.2s_ease-out]"
        onclick={(e) => e.stopPropagation()}
        onkeydown={(e) => e.stopPropagation()}
        role="dialog"
      >
        <!-- Windows Header style -->
        <div class="flex items-center gap-2 px-4 py-3 bg-zinc-50 border-b-2 border-black shrink-0 select-none">
          <div class="w-2.5 h-2.5 rounded-full bg-red-500 border border-black"></div>
          <div class="w-2.5 h-2.5 rounded-full bg-yellow-500 border border-black"></div>
          <div class="w-2.5 h-2.5 rounded-full bg-green-500 border border-black"></div>
          <span class="text-xs font-bold text-zinc-500 ml-2 font-black">Chi tiết sự cố</span>
          <button 
            onclick={() => isDetailOpen = false} 
            class="ml-auto text-black hover:bg-zinc-200 p-1 border border-transparent rounded-[6px] cursor-pointer"
          >
            <X class="h-4.5 w-4.5" />
          </button>
        </div>

        <div class="p-6 space-y-6 flex-1 overflow-y-auto">
          <!-- Drawer Header Details -->
          <div class="flex items-center gap-3 border-b-2 border-black pb-4">
            <div class="bg-white border-2 border-black p-2.5 rounded-lg shadow-secondary text-black shrink-0">
              <Wrench class="h-6 w-6" />
            </div>
            <div>
              <h3 class="font-black text-black text-lg leading-tight">Yêu Cầu Sửa Chữa</h3>
              <p class="text-zinc-600 text-xs mt-0.5 font-bold">
                Phòng {selectedRequest.roomNumber} ({selectedRequest.buildingName})
              </p>
            </div>
          </div>

          <!-- Metadata table -->
          <div class="grid grid-cols-2 gap-4 text-xs bg-white p-4 border-2 border-black rounded-lg shadow-secondary text-black font-semibold">
            <div>
              <p class="text-zinc-500 uppercase tracking-wide font-bold text-[9px]">Khách báo sự cố</p>
              <p class="font-black text-black mt-0.5">{selectedRequest.tenant.user.name} ({selectedRequest.tenant.user.phone})</p>
            </div>
            <div>
              <p class="text-zinc-500 uppercase tracking-wide font-bold text-[9px]">Ngày gửi báo cáo</p>
              <p class="font-black text-black mt-0.5 flex items-center gap-1">
                <Calendar class="h-3.5 w-3.5 text-black" />
                {new Date(selectedRequest.createdAt).toLocaleDateString('vi-VN')}
              </p>
            </div>
            <div>
              <p class="text-zinc-500 uppercase tracking-wide font-bold text-[9px]">Danh mục kỹ thuật</p>
              <p class="font-black text-black mt-0.5">{getCategoryLabel(selectedRequest.category)}</p>
            </div>
            <div>
              <p class="text-zinc-500 uppercase tracking-wide font-bold text-[9px]">Mức độ ưu tiên</p>
              <p class="font-black mt-0.5 {selectedRequest.priority === 'important' ? 'text-red-650 animate-pulse' : 'text-black'}">
                {selectedRequest.priority === 'important' ? 'Khẩn cấp / Gấp' : 'Bình thường'}
              </p>
            </div>
          </div>

          <!-- Ticket Content -->
          <div class="space-y-2">
            <h4 class="text-xs font-black text-zinc-500 uppercase tracking-wider">Mô tả sự cố</h4>
            <div class="bg-white border-2 border-black p-4 rounded-lg shadow-secondary space-y-2 text-black">
              <h5 class="font-black text-black text-sm">{selectedRequest.title}</h5>
              <p class="text-zinc-650 text-xs leading-relaxed font-semibold">{selectedRequest.description}</p>
            </div>
          </div>

          <!-- Incident Image -->
          {#if selectedRequest.imageUrl}
            <div class="space-y-2">
              <h4 class="text-xs font-black text-zinc-500 uppercase tracking-wider">Ảnh đính kèm</h4>
              <img 
                src={selectedRequest.imageUrl} 
                alt="Anh su co" 
                class="rounded-lg max-h-64 w-full object-contain border-2 border-black shadow-secondary bg-white"
              />
            </div>
          {/if}

          <!-- Response Reply -->
          <div class="space-y-2">
            <label for="req-reply" class="text-xs font-black text-zinc-650 uppercase tracking-wider block">Phản hồi của chủ nhà / Biên bản sửa chữa</label>
            <textarea
              id="req-reply"
              bind:value={replyText}
              placeholder="Nhập ghi chú sửa chữa, ngày hoàn thành hoặc phản hồi cho cư dân biết..."
              rows="3"
              class="w-full border-2 border-black p-3 text-xs rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-300 bg-white font-semibold text-black"
            ></textarea>
          </div>
        </div>

        <!-- Action update footer buttons -->
        <div class="p-6 border-t-2 border-black bg-zinc-150 flex flex-wrap gap-3 shrink-0">
          <button
            onclick={() => updateRequestStatus(selectedRequest!.id, 'in_progress')}
            disabled={isSubmitting}
            class="flex-1 min-w-[100px] border-2 border-black bg-blue-300 hover:bg-blue-400 text-black py-2.5 rounded-[6px] text-xs font-black shadow-secondary hover:translate-x-[2px] hover:translate-y-[2px] hover:shadow-none transition-all cursor-pointer"
          >
            Đang sửa
          </button>
          
          <button
            onclick={() => updateRequestStatus(selectedRequest!.id, 'completed')}
            disabled={isSubmitting}
            class="flex-grow min-w-[100px] bg-green-200 hover:bg-green-300 text-black border-2 border-black py-2.5 rounded-[6px] text-xs font-black shadow-secondary hover:translate-x-[2px] hover:translate-y-[2px] hover:shadow-none transition-all flex items-center justify-center gap-1.5 cursor-pointer"
          >
            Đã xong <Check class="h-4 w-4" />
          </button>
          
          <button
            onclick={() => updateRequestStatus(selectedRequest!.id, 'rejected')}
            disabled={isSubmitting}
            class="border-2 border-black bg-red-200 hover:bg-red-300 text-red-800 py-2.5 px-4 rounded-[6px] text-xs font-black shadow-secondary hover:translate-x-[2px] hover:translate-y-[2px] hover:shadow-none transition-all cursor-pointer"
          >
            Từ chối
          </button>
        </div>
      </div>
    </div>
  {/if}

</div>
