// app/dashboard/page.tsx
'use client';

import { useState, useEffect } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table';
import { DollarSign, Home, Receipt, Calendar, Send, Check, Loader2, Bell, MessageSquare, Clock, Play, CheckCircle2 } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { mockRooms, mockInvoices, dashboardStats, buildings, calculateBuildingStats, getBuildingById, type Invoice } from '@/lib/data';
import { toast } from 'sonner';

export default function DashboardPage() {
  const router = useRouter();
  const [today, setToday] = useState<string>('');
  const [processingInvoiceId, setProcessingInvoiceId] = useState<string | null>(null);

  useEffect(() => {
    setToday(new Date().toLocaleDateString('vi-VN', { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' }));
  }, []);

  const formatCurrency = (amount: number) => {
    return new Intl.NumberFormat('vi-VN').format(amount) + 'đ';
  };

  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleDateString('vi-VN');
  };

  // Get unpaid invoices
  const unpaidInvoices = mockInvoices.filter(i => i.status !== 'paid').slice(0, 5);

  // Mock notifications for dashboard
  const recentNotifications = [
    {
      id: '1',
      title: 'Hóa đơn quá hạn',
      description: 'P.101 - HAGL1 quá hạn 3 ngày',
      time: '5 phút trước',
      type: 'warning' as const,
      isRead: false,
    },
    {
      id: '2',
      title: 'Thanh toán thành công',
      description: 'P.205 - HAGL2 đã thanh toán 5,500,000đ',
      time: '1 giờ trước',
      type: 'success' as const,
      isRead: false,
    },
    {
      id: '3',
      title: 'Khách mới',
      description: 'Nguyễn Văn A đã được thêm vào P.302',
      time: '2 giờ trước',
      type: 'info' as const,
      isRead: true,
    },
  ];

  // Mock requests for dashboard
  const [pendingRequests, setPendingRequests] = useState([
    {
      id: '1',
      room: 'P.101',
      building: 'HAGL1',
      tenant: 'Nguyễn Văn A',
      title: 'Máy lạnh không hoạt động',
      category: 'electrical',
      time: '2 giờ trước',
      status: 'pending' as const,
      priority: 'important' as const,
    },
    {
      id: '2',
      room: 'P.205',
      building: 'HAGL2',
      tenant: 'Trần Thị B',
      title: 'Bồn cầu bị nghẹt',
      category: 'plumbing',
      time: '5 giờ trước',
      status: 'in_progress' as const,
      priority: 'important' as const,
    },
    {
      id: '3',
      room: 'P.302',
      building: 'HAGL1',
      tenant: 'Lê Văn C',
      title: 'Wifi yếu',
      category: 'internet',
      time: '1 ngày trước',
      status: 'pending' as const,
      priority: 'normal' as const,
    },
  ]);

  const getNotificationTypeColor = (type: 'warning' | 'success' | 'info') => {
    switch (type) {
      case 'warning': return 'bg-amber-500';
      case 'success': return 'bg-emerald-500';
      case 'info': return 'bg-blue-500';
    }
  };

  const getRequestPriorityBadge = (priority: 'important' | 'normal') => {
    switch (priority) {
      case 'important':
        return <Badge variant="outline" className="bg-red-50 text-red-700 border-red-200">Quan trọng</Badge>;
      case 'normal':
        return <Badge variant="outline" className="bg-slate-50 text-slate-700 border-slate-200">Thông thường</Badge>;
    }
  };

  const handleRequestStatusChange = (id: string, e: React.MouseEvent) => {
    e.stopPropagation();
    setPendingRequests(prev => prev.map(req => {
      if (req.id === id) {
        if (req.status === 'pending') {
          toast.success('Đã chuyển sang đang xử lý');
          return { ...req, status: 'in_progress' as const };
        } else if (req.status === 'in_progress') {
          toast.success('Đã hoàn thành yêu cầu');
          return { ...req, status: 'completed' as const };
        }
      }
      return req;
    }));
  };

  // Quick actions
  const handleQuickPay = async (invoice: Invoice, e: React.MouseEvent) => {
    e.stopPropagation();
    setProcessingInvoiceId(invoice.id);

    await new Promise(resolve => setTimeout(resolve, 1000));

    toast.success('Đã xác nhận thanh toán', {
      description: `P.${invoice.roomNumber} - ${formatCurrency(invoice.totalAmount)}`,
    });

    setProcessingInvoiceId(null);
  };

  const handleQuickSendZalo = async (invoice: Invoice, e: React.MouseEvent) => {
    e.stopPropagation();

    toast.info('Đang khởi tạo liên kết Zalo...', {
      description: `Gửi nhắc nhở cho ${invoice.tenantName}`,
    });

    await new Promise(resolve => setTimeout(resolve, 1000));

    toast.success('Đã mở Zalo', {
      description: 'Tin nhắn đã được chuẩn bị sẵn',
    });
  };

  const handleInvoiceRowClick = (invoice: Invoice) => {
    router.push(`/dashboard/invoices?search=${invoice.id}`);
  };

  return (
    <div className="space-y-8">
      {/* Header */}
      <div>
        <h1 className="text-2xl font-bold">Tổng quan</h1>
        <p className="text-muted-foreground">{today && `Hôm nay, ${today}`}</p>
      </div>

      {/* 1. Tình trạng */}
      <div>
        <h2 className="text-lg font-semibold mb-4">Tình trạng</h2>
        <div className="grid grid-cols-2 lg:grid-cols-4 gap-3 sm:gap-4">
        <Card className="border-2 border-blue-200 hover:border-blue-400 transition-colors">
          <CardContent className="p-3 sm:p-5">
            <div className="flex items-center gap-2 sm:gap-3">
              <DollarSign className="h-5 w-5 sm:h-6 sm:w-6 text-blue-600 shrink-0" />
              <div className="min-w-0">
                <p className="text-xs sm:text-sm text-muted-foreground">Doanh thu tháng</p>
                <p className="text-base sm:text-xl font-bold truncate">{formatCurrency(dashboardStats.totalRevenue)}</p>
              </div>
            </div>
          </CardContent>
        </Card>
        <Card className="border-2 border-blue-200 hover:border-blue-400 transition-colors">
          <CardContent className="p-3 sm:p-5">
            <div className="flex items-center gap-2 sm:gap-3">
              <Home className="h-5 w-5 sm:h-6 sm:w-6 text-blue-600 shrink-0" />
              <div className="min-w-0">
                <p className="text-xs sm:text-sm text-muted-foreground">Phòng trống</p>
                <p className="text-base sm:text-xl font-bold">{dashboardStats.emptyRooms} <span className="text-xs sm:text-sm font-normal text-muted-foreground">/ {mockRooms.length}</span></p>
              </div>
            </div>
          </CardContent>
        </Card>
        <Card className="border-2 border-blue-200 hover:border-blue-400 transition-colors">
          <CardContent className="p-3 sm:p-5">
            <div className="flex items-center gap-2 sm:gap-3">
              <Receipt className="h-5 w-5 sm:h-6 sm:w-6 text-blue-600 shrink-0" />
              <div className="min-w-0">
                <p className="text-xs sm:text-sm text-muted-foreground">Chưa thu tiền</p>
                <p className="text-base sm:text-xl font-bold">{dashboardStats.unpaidInvoices} <span className="text-xs sm:text-sm font-normal text-muted-foreground">hóa đơn</span></p>
              </div>
            </div>
          </CardContent>
        </Card>
        <Card className="border-2 border-blue-200 hover:border-blue-400 transition-colors">
          <CardContent className="p-3 sm:p-5">
            <div className="flex items-center gap-2 sm:gap-3">
              <Calendar className="h-5 w-5 sm:h-6 sm:w-6 text-blue-600 shrink-0" />
              <div className="min-w-0">
                <p className="text-xs sm:text-sm text-muted-foreground">Sắp hết hạn HĐ</p>
                <p className="text-base sm:text-xl font-bold">{dashboardStats.expiringContracts} <span className="text-xs sm:text-sm font-normal text-muted-foreground">khách</span></p>
              </div>
            </div>
          </CardContent>
        </Card>
        </div>
      </div>

      {/* 2. Yêu cầu của khách */}
      <div>
        <div className="flex items-center justify-between mb-4">
          <div className="flex items-center gap-2">
            <MessageSquare className="h-5 w-5 text-muted-foreground" />
            <h2 className="text-lg font-semibold">Yêu cầu của khách</h2>
            <Badge variant="outline" className="h-5 px-1.5 bg-amber-50 text-amber-700 border-amber-200">
              {pendingRequests.filter(r => r.status !== 'completed').length} yêu cầu
            </Badge>
          </div>
          <Link href="/dashboard/requests">
            <Button variant="outline" size="sm">Xem tất cả</Button>
          </Link>
        </div>
        <Card>
          <CardContent className="p-0">
            {pendingRequests.filter(r => r.status !== 'completed').length > 0 ? (
              <div className="divide-y">
                {pendingRequests.filter(r => r.status !== 'completed').map((request) => (
                  <div
                    key={request.id}
                    className="p-4 hover:bg-muted/50 transition-colors"
                  >
                    <div className="flex items-start justify-between gap-3">
                      <div className="flex-1 min-w-0">
                        <div className="flex items-center gap-2 mb-1">
                          <span className="font-medium text-sm">{request.room}</span>
                          <span className="text-xs text-muted-foreground">• {request.building}</span>
                          {getRequestPriorityBadge(request.priority)}
                        </div>
                        <p className="text-sm truncate">{request.title}</p>
                        <p className="text-xs text-muted-foreground mt-1">{request.tenant} • {request.time}</p>
                      </div>
                      <div className="shrink-0 flex items-center gap-2">
                        {request.status === 'pending' ? (
                          <Button
                            variant="outline"
                            size="sm"
                            className="h-8 text-xs"
                            onClick={(e) => handleRequestStatusChange(request.id, e)}
                          >
                            <Play className="h-3 w-3 mr-1" />
                            Xử lý
                          </Button>
                        ) : request.status === 'in_progress' ? (
                          <Button
                            variant="outline"
                            size="sm"
                            className="h-8 text-xs text-emerald-600 border-emerald-200 hover:bg-emerald-50"
                            onClick={(e) => handleRequestStatusChange(request.id, e)}
                          >
                            <CheckCircle2 className="h-3 w-3 mr-1" />
                            Hoàn thành
                          </Button>
                        ) : null}
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            ) : (
              <p className="p-6 text-center text-muted-foreground">Không có yêu cầu nào</p>
            )}
          </CardContent>
        </Card>
      </div>

      {/* 3. Hóa đơn chưa thu */}
      <div>
        <div className="flex items-center justify-between mb-4">
          <h2 className="text-lg font-semibold">Hóa đơn chưa thu</h2>
          <Link href="/dashboard/invoices">
            <Button variant="outline" size="sm">Xem tất cả</Button>
          </Link>
        </div>
        <Card>
          <CardContent className="p-0">
            {unpaidInvoices.length > 0 ? (
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Phòng</TableHead>
                    <TableHead>Khách thuê</TableHead>
                    <TableHead className="text-right">Số tiền</TableHead>
                    <TableHead className="hidden sm:table-cell">Hạn thu</TableHead>
                    <TableHead>Tình trạng</TableHead>
                    <TableHead className="text-right">Thao tác</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {unpaidInvoices.map((invoice) => {
                    const building = getBuildingById(invoice.buildingId);
                    const isOverdue = invoice.status === 'overdue';
                    const isProcessing = processingInvoiceId === invoice.id;
                    return (
                      <TableRow
                        key={invoice.id}
                        className="cursor-pointer hover:bg-muted/50 transition-colors"
                        onClick={() => handleInvoiceRowClick(invoice)}
                      >
                        <TableCell>
                          <div className="font-medium">P.{invoice.roomNumber}</div>
                          <div className="text-sm text-muted-foreground">{building?.shortName}</div>
                        </TableCell>
                        <TableCell>{invoice.tenantName}</TableCell>
                        <TableCell className="text-right font-medium">{formatCurrency(invoice.totalAmount)}</TableCell>
                        <TableCell className="hidden sm:table-cell">{formatDate(invoice.dueDate)}</TableCell>
                        <TableCell>
                          <span className={isOverdue ? 'text-red-600 font-medium' : ''}>
                            {isOverdue ? 'Quá hạn' : 'Chờ thu'}
                          </span>
                        </TableCell>
                        <TableCell>
                          <div className="flex items-center justify-end gap-1">
                            <Button
                              variant="ghost"
                              size="icon"
                              className="h-8 w-8"
                              onClick={(e) => handleQuickSendZalo(invoice, e)}
                              title="Gửi Zalo"
                            >
                              <Send className="h-4 w-4" />
                            </Button>
                            <Button
                              variant="ghost"
                              size="icon"
                              className="h-8 w-8 text-emerald-600 hover:text-emerald-700 hover:bg-emerald-50"
                              onClick={(e) => handleQuickPay(invoice, e)}
                              disabled={isProcessing}
                              title="Xác nhận đã thu"
                            >
                              {isProcessing ? (
                                <Loader2 className="h-4 w-4 animate-spin" />
                              ) : (
                                <Check className="h-4 w-4" />
                              )}
                            </Button>
                          </div>
                        </TableCell>
                      </TableRow>
                    );
                  })}
                </TableBody>
              </Table>
            ) : (
              <p className="p-6 text-center text-muted-foreground">Không có hóa đơn chưa thu</p>
            )}
          </CardContent>
        </Card>
      </div>

      {/* 4. Doanh thu theo tòa nhà */}
      <div>
        <div className="flex items-center justify-between mb-4">
          <h2 className="text-lg font-semibold">Doanh thu theo tòa nhà</h2>
          <Link href="/dashboard/buildings">
            <Button variant="outline" size="sm">Xem chi tiết</Button>
          </Link>
        </div>
        <Card>
          <CardContent className="p-0">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Tòa nhà</TableHead>
                  <TableHead className="text-right">Doanh thu tháng</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {buildings.map((building) => {
                  const stats = calculateBuildingStats(mockRooms, building.id);
                  return (
                    <TableRow key={building.id}>
                      <TableCell className="font-medium">
                        <Link href={`/dashboard/rooms?building=${building.id}`} className="hover:underline">
                          {building.name}
                        </Link>
                      </TableCell>
                      <TableCell className="text-right font-medium text-emerald-600">
                        {formatCurrency(stats.revenue)}
                      </TableCell>
                    </TableRow>
                  );
                })}
              </TableBody>
            </Table>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}

// src/routes/dashboard/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { goto } from '$app/navigation';
  import { toast } from 'svelte-sonner';
  import { 
    DollarSign, 
    Home, 
    Receipt, 
    Calendar, 
    Check, 
    Loader2, 
    Play, 
    CheckCircle2, 
    User,
    ArrowRight,
    Wrench
  } from '@lucide/svelte';

  interface DashboardStats {
    totalRevenue: number;
    emptyRooms: number;
    unpaidInvoices: number;
    expiringContracts: number;
    totalRooms: number;
    occupiedRooms: number;
  }

  interface Invoice {
    id: string;
    roomNumber: string;
    tenantName: string;
    tenantPhone: string;
    month: string;
    totalAmount: number;
    dueDate: string;
    status: string;
    room: {
      property: {
        shortName: string;
      }
    };
  }

  interface MaintenanceRequest {
    id: string;
    roomNumber: string;
    buildingName: string;
    tenant: {
      user: {
        name: string;
      }
    };
    title: string;
    status: string;
    priority: string;
    createdAt: string;
  }

  let today = $state('');
  let landlordId = $state<string | null>(null);
  let isLoading = $state(true);
  let processingInvoiceId = $state<string | null>(null);

  let stats = $state<DashboardStats>({
    totalRevenue: 0,
    emptyRooms: 0,
    unpaidInvoices: 0,
    expiringContracts: 0,
    totalRooms: 0,
    occupiedRooms: 0
  });

  let unpaidInvoices = $state<Invoice[]>([]);
  let pendingRequests = $state<MaintenanceRequest[]>([]);

  onMount(() => {
    today = new Date().toLocaleDateString('vi-VN', { 
      weekday: 'long', 
      day: 'numeric', 
      month: 'long', 
      year: 'numeric' 
    });

    const sessionStr = localStorage.getItem('roomio_user');
    if (!sessionStr) {
      goto('/login');
      return;
    }
    const session = JSON.parse(sessionStr);
    landlordId = session.landlordProfileId;
    fetchDashboardData(session.landlordProfileId);
  });

  async function fetchDashboardData(profileId: string) {
    isLoading = true;
    try {
      // 1. Fetch dashboard stats
      const statsRes = await fetch(`/api/dashboard/stats?landlordId=${profileId}`);
      const statsData = await statsRes.json();
      if (statsRes.ok) stats = statsData;

      // 2. Fetch pending invoices
      const invRes = await fetch(`/api/invoices?landlordId=${profileId}&status=pending`);
      const invData = await invRes.json();
      if (invRes.ok) unpaidInvoices = invData.slice(0, 5);

      // 3. Fetch requests
      const reqRes = await fetch(`/api/requests?landlordId=${profileId}`);
      const reqData = await reqRes.json();
      if (reqRes.ok) {
        pendingRequests = reqData
          .filter((r: any) => r.status !== 'completed' && r.status !== 'rejected')
          .slice(0, 5);
      }
    } catch (err: any) {
      toast.error('Không thể tải dữ liệu báo cáo: ' + err.message);
    } finally {
      isLoading = false;
    }
  }

  async function confirmInvoicePayment(invoiceId: string) {
    if (processingInvoiceId) return;
    processingInvoiceId = invoiceId;

    try {
      const res = await fetch(`/api/invoices/${invoiceId}`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ action: 'confirmPaid' })
      });
      const data = await res.json();

      if (!res.ok) {
        throw new Error(data.error || 'Lỗi khi xác nhận đóng tiền');
      }

      toast.success(`Đã xác nhận thanh toán hóa đơn ${invoiceId}`);
      // Refresh
      if (landlordId) fetchDashboardData(landlordId);
    } catch (err: any) {
      toast.error(err.message);
    } finally {
      processingInvoiceId = null;
    }
  }

  function formatCurrency(amount: number) {
    return new Intl.NumberFormat('vi-VN').format(amount) + 'đ';
  }
</script>

<div class="space-y-6">
  <!-- Header -->
  <div class="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
    <div>
      <h1 class="text-xl sm:text-2xl font-black text-black">Cổng Quản Trị Roomio</h1>
      <p class="text-zinc-600 text-xs sm:text-sm mt-1 flex items-center gap-1.5 font-bold">
        Hôm nay, {today} <Calendar class="h-4 w-4 text-zinc-500" />
      </p>
    </div>
    <div class="flex gap-2 sm:gap-3">
      <a 
        href="/dashboard/rooms" 
        class="flex-1 sm:flex-none bg-blue-300 text-black border-2 border-black px-3 sm:px-4 py-2 sm:py-2.5 rounded-[6px] shadow-secondary hover:translate-x-[2px] hover:translate-y-[2px] hover:shadow-none transition-all flex items-center justify-center gap-1.5 cursor-pointer font-black text-xs sm:text-sm"
      >
        Phòng <ArrowRight class="h-3.5 w-3.5" />
      </a>
      <a 
        href="/dashboard/invoices/bulk" 
        class="flex-1 sm:flex-none bg-green-200 text-black border-2 border-black px-3 sm:px-4 py-2 sm:py-2.5 rounded-[6px] shadow-secondary hover:translate-x-[2px] hover:translate-y-[2px] hover:shadow-none transition-all flex items-center justify-center gap-1.5 cursor-pointer font-black text-xs sm:text-sm"
      >
        Hoá đơn loạt <Play class="h-3.5 w-3.5" />
      </a>
    </div>
  </div>

  {#if isLoading}
    <div class="h-[60vh] w-full flex items-center justify-center">
      <div class="flex flex-col items-center gap-3">
        <Loader2 class="h-10 w-10 text-black animate-spin" />
        <p class="text-zinc-600 font-bold">Đang tải báo cáo tổng quan...</p>
      </div>
    </div>
  {:else}
    <!-- Stats Cards Grid: 2 cols mobile, 4 cols desktop -->
    <div class="grid grid-cols-2 lg:grid-cols-4 gap-3">
      <!-- Card 1: Revenue -->
      <div class="bg-white border-2 border-black p-4 rounded-lg shadow-secondary">
        <DollarSign class="h-5 w-5 text-blue-500 mb-2" />
        <p class="text-zinc-500 text-[10px] font-bold uppercase tracking-wider">Doanh thu</p>
        <h3 class="text-base sm:text-xl font-black text-black mt-0.5 truncate">{formatCurrency(stats.totalRevenue)}</h3>
      </div>

      <!-- Card 2: Occupancy -->
      <div class="bg-white border-2 border-black p-4 rounded-lg shadow-secondary">
        <Home class="h-5 w-5 text-blue-500 mb-2" />
        <p class="text-zinc-500 text-[10px] font-bold uppercase tracking-wider">Tỷ lệ trống</p>
        <h3 class="text-base sm:text-xl font-black text-black mt-0.5">
          {stats.emptyRooms}/{stats.totalRooms}
          <span class="text-[10px] font-bold text-zinc-400 block">
            Lấp đầy {stats.totalRooms > 0 ? Math.round((stats.occupiedRooms / stats.totalRooms) * 100) : 0}%
          </span>
        </h3>
      </div>

      <!-- Card 3: Unpaid Bills -->
      <div class="bg-white border-2 border-black p-4 rounded-lg shadow-secondary">
        <Receipt class="h-5 w-5 text-blue-500 mb-2" />
        <p class="text-zinc-500 text-[10px] font-bold uppercase tracking-wider">Chưa đóng</p>
        <h3 class="text-base sm:text-xl font-black text-black mt-0.5">{stats.unpaidInvoices} HĐ</h3>
      </div>

      <!-- Card 4: Expiring Contracts -->
      <div class="bg-white border-2 border-black p-4 rounded-lg shadow-secondary">
        <Calendar class="h-5 w-5 text-blue-500 mb-2" />
        <p class="text-zinc-500 text-[10px] font-bold uppercase tracking-wider">Sắp hết HĐ</p>
        <h3 class="text-base sm:text-xl font-black text-black mt-0.5">{stats.expiringContracts}</h3>
      </div>
    </div>

    <!-- Main Lists Section -->
    <div class="grid gap-6 lg:grid-cols-3">
      <!-- Left 2 Columns: Unpaid Invoices -->
      <div class="lg:col-span-2 bg-white border-2 border-black rounded-lg shadow-secondary flex flex-col overflow-hidden">
        <div class="p-4 border-b-2 border-black bg-zinc-50 flex items-center justify-between shrink-0">
          <h2 class="font-black text-black text-base flex items-center gap-2">
            Hoá đơn cần thu tiền <Receipt class="h-5 w-5" />
          </h2>
          <a href="/dashboard/invoices" class="text-xs font-black text-blue-500 hover:underline flex items-center gap-1">
            Xem tất cả <ArrowRight class="h-3.5 w-3.5" />
          </a>
        </div>

        {#if unpaidInvoices.length === 0}
          <div class="flex-1 p-8 flex flex-col items-center justify-center text-center bg-white">
            <CheckCircle2 class="h-12 w-12 text-green-500 mb-2" />
            <p class="font-black text-black text-base">Tất cả sạch nợ!</p>
            <p class="text-zinc-500 text-xs font-semibold mt-1">Không có hoá đơn nào đang nợ hoặc chưa đóng.</p>
          </div>
        {:else}
          <!-- Mobile: card list view -->
          <div class="sm:hidden divide-y-2 divide-black bg-white">
            {#each unpaidInvoices as invoice}
              <div class="p-4 space-y-2">
                <div class="flex justify-between items-start gap-2">
                  <div class="min-w-0">
                    <p class="font-black text-black text-sm">{invoice.room.property.shortName} - P.{invoice.roomNumber}</p>
                    <p class="text-xs text-zinc-500 font-bold mt-0.5 truncate">{invoice.tenantName} · T.{invoice.month}</p>
                  </div>
                  <span class="text-sm font-black text-black shrink-0">{formatCurrency(invoice.totalAmount)}</span>
                </div>
                <div class="flex items-center justify-between gap-2">
                  <span class="text-[10px] px-2 py-0.5 rounded-full font-bold bg-red-100 border border-black text-red-800 shrink-0">
                    HN: {new Date(invoice.dueDate).toLocaleDateString('vi-VN')}
                  </span>
                  <button
                    onclick={() => confirmInvoicePayment(invoice.id)}
                    disabled={processingInvoiceId === invoice.id}
                    class="px-3 py-1.5 bg-green-200 disabled:opacity-50 text-black border-2 border-black rounded-[6px] shadow-secondary hover:translate-x-[2px] hover:translate-y-[2px] hover:shadow-none transition-all flex items-center gap-1 cursor-pointer font-black text-xs"
                  >
                    {#if processingInvoiceId === invoice.id}
                      <Loader2 class="h-3 w-3 animate-spin" />
                    {:else}
                      Xác nhận <Check class="h-3 w-3" />
                    {/if}
                  </button>
                </div>
              </div>
            {/each}
          </div>
          <!-- Desktop: table view -->
          <div class="hidden sm:block overflow-x-auto bg-white">
            <table class="w-full text-left border-collapse text-sm">
              <thead>
                <tr class="bg-blue-300 border-b-2 border-black text-black font-black uppercase text-xs">
                  <th class="px-4 py-3">Phòng</th>
                  <th class="px-4 py-3">Khách thuê</th>
                  <th class="px-4 py-3">Tháng</th>
                  <th class="px-4 py-3">Số tiền</th>
                  <th class="px-4 py-3">Hạn thanh toán</th>
                  <th class="px-4 py-3 text-right">Thao tác</th>
                </tr>
              </thead>
              <tbody>
                {#each unpaidInvoices as invoice}
                  <tr class="border-b border-black/15 hover:bg-slate-50 transition-all font-semibold">
                    <td class="px-4 py-4 font-black text-black">
                      {invoice.room.property.shortName} - {invoice.roomNumber}
                    </td>
                    <td class="px-4 py-4">
                      <div>
                        <p class="font-black text-black text-sm">{invoice.tenantName}</p>
                        <p class="text-xs text-zinc-500 font-bold">{invoice.tenantPhone}</p>
                      </div>
                    </td>
                    <td class="px-4 py-4 font-bold">{invoice.month}</td>
                    <td class="px-4 py-4 font-black text-black">{formatCurrency(invoice.totalAmount)}</td>
                    <td class="px-4 py-4">
                      <span class="text-xs px-2.5 py-0.5 rounded-full font-bold bg-red-100 border border-black text-red-800">
                        {new Date(invoice.dueDate).toLocaleDateString('vi-VN')}
                      </span>
                    </td>
                    <td class="px-4 py-4 text-right">
                      <button
                        onclick={() => confirmInvoicePayment(invoice.id)}
                        disabled={processingInvoiceId === invoice.id}
                        class="px-3 py-1.5 bg-green-200 hover:bg-green-300 disabled:opacity-50 text-black border-2 border-black rounded-[6px] shadow-secondary hover:translate-x-[2px] hover:translate-y-[2px] hover:shadow-none transition-all flex items-center justify-center ml-auto gap-1 cursor-pointer font-black text-xs"
                      >
                        Xác nhận đóng
                        {#if processingInvoiceId === invoice.id}
                          <Loader2 class="h-3 w-3 animate-spin" />
                        {:else}
                          <Check class="h-3.5 w-3.5" />
                        {/if}
                      </button>
                    </td>
                  </tr>
                {/each}
              </tbody>
            </table>
          </div>
        {/if}
      </div>

      <!-- Right Column: Pending Incidents -->
      <div class="bg-white border-2 border-black rounded-lg shadow-secondary flex flex-col overflow-hidden">
        <div class="p-4 border-b-2 border-black bg-zinc-50 flex items-center justify-between shrink-0">
          <h2 class="font-black text-black text-base flex items-center gap-2">
            Sự cố cần xử lý <Wrench class="h-5 w-5" />
          </h2>
          <a href="/dashboard/requests" class="text-xs font-black text-blue-500 hover:underline flex items-center gap-1">
            Xem tất cả <ArrowRight class="h-3.5 w-3.5" />
          </a>
        </div>

        {#if pendingRequests.length === 0}
          <div class="flex-1 p-8 flex flex-col items-center justify-center text-center bg-white">
            <CheckCircle2 class="h-12 w-12 text-green-500 mb-2" />
            <p class="font-black text-black text-base">Không có sự cố nào!</p>
            <p class="text-zinc-500 text-xs font-semibold mt-1">Nhà trọ vận hành êm đẹp, chưa ghi nhận vấn đề.</p>
          </div>
        {:else}
          <div class="divide-y-2 divide-black flex-1 overflow-y-auto bg-white">
            {#each pendingRequests as req}
              <div class="p-4 hover:bg-slate-50 transition-all flex flex-col gap-2 font-semibold">
                <div class="flex items-start justify-between gap-3">
                  <div>
                    <h4 class="font-black text-black text-sm">{req.title}</h4>
                    <p class="text-xs text-zinc-500 font-bold mt-0.5">{req.buildingName} - Phòng {req.roomNumber}</p>
                  </div>
                  <span class="text-[10px] px-2 py-0.5 rounded-full font-black uppercase border border-black {req.priority === 'important' ? 'bg-red-200 text-red-800' : 'bg-zinc-150 text-zinc-700'}">
                    {req.priority === 'important' ? 'Khẩn cấp' : 'Thường'}
                  </span>
                </div>
                <div class="flex items-center justify-between text-xs text-zinc-500 font-bold mt-1">
                  <span class="flex items-center gap-1">
                    <User class="h-3.5 w-3.5" />
                    {req.tenant.user.name}
                  </span>
                  <span>{new Date(req.createdAt).toLocaleDateString('vi-VN')}</span>
                </div>
                <div class="flex gap-2 mt-2">
                  <a 
                    href="/dashboard/requests" 
                    class="px-3 py-1.5 bg-blue-300 hover:bg-blue-400 text-black border-2 border-black rounded-[6px] shadow-secondary hover:translate-x-[2px] hover:translate-y-[2px] hover:shadow-none transition-all text-xs font-black text-center flex items-center justify-center gap-1.5 cursor-pointer w-full"
                  >
                    Chi tiết & Phân công <ArrowRight class="h-3.5 w-3.5" />
                  </a>
                </div>
              </div>
            {/each}
          </div>
        {/if}
      </div>
    </div>
  {/if}
</div>
